# Load Daily Data into S3 Bucket

### Obtaining Data


We use the dataset generated by [Chi Zhang](https://github.com/vermouth1992/drl-portfolio-management/tree/master/src/utils/datasets). It contains the historic price of 16 target stocks from NASDAQ100, including open, close, high and low prices from 2012-08-13 to 2017-08-11. Specifically, those stocks are: “AAPL”, “ATVI”, “CMCSA”, “COST”, “CSX”, “DISH”, “EA”, “EBAY”, “FB”, “GOOGL”, “HAS”, “ILMN”, “INTC”, “MAR”, “REGN” and “SBUX”.

**This dataset is licensed under a MIT License**

Copyright (c) 2017 Chi Zhang

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

### Output dataset 

- Contains 5 years of EOD data for one of the stocks
- The data is saved into the specified S3 bucket as CSV.

```
hist_data_daily/{sym}.csv (columns: dt,sym,open,high,low,close,vol)
```

In [6]:
# get S3 bucket
s3bucket=!(aws s3 ls | grep algotrading- | awk  '{print $3}')
s3bucket=s3bucket[0]
s3bucket

'algotrading-demo-ver1'

In [7]:
# symbol
sym='INTC'

In [8]:
%run data_prep.py {sym}

store:INTC

In [9]:
import pandas as pd

df = pd.read_csv("INTC.csv",parse_dates=['dt'], index_col=['dt'])
df.head()

             sym   open   high    low  close         vol
dt
2012-08-13  INTC  26.76  26.83  26.41  26.69  23623918.0
2012-08-14  INTC  26.80  26.81  26.38  26.48  27477260.0
2012-08-15  INTC  26.23  26.47  26.19  26.27  26081909.0
2012-08-16  INTC  26.44  26.65  26.34  26.59  25702363.0
2012-08-17  INTC  26.57  26.63  26.21  26.33  30379903.0

In [10]:
!aws s3 cp {sym}.csv s3://{s3bucket}/hist_data_daily/
!rm {sym}.csv

upload: ./INTC.csv to s3://algotrading-demo-ver1/hist_data_daily/INTC.csv